{% set name = "medcam" %}
{% set version = "0.1.21" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 97eeafc89335f6b2ad5a3c032a5e2f92a98962faa4425e2eb8ef0b4cb12866fd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - certifi
    - cycler
    - decorator
    - future
    - imageio
    - kiwisolver
    - mako
    - markdown
    - markupsafe
    - matplotlib-base
    - networkx
    - nibabel
    - numpy
    - opencv
    - packaging
    - pandas
    - pillow
    - pyparsing
    - python >={{ python_min }}
    - python-dateutil
    - pytz
    - pywavelets
    - scikit-image
    - scipy
    - simpleitk
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - medcam

about:
  home: https://pypi.org/project/medcam/
  summary: An easy to use library that makes model predictions more interpretable for humans.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://meclabtuda.github.io/M3d-Cam
  dev_url: https://github.com/MECLabTUDA/M3d-Cam

extra:
  recipe-maintainers:
    - sarthakpati
