{% set name = "medcam" %}
{% set version = "0.1.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ec442b76331917e4899ae475eae3045da8ab03d09686d0e2e5bbb056e49c669

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - certifi
    - cycler
    - decorator
    - future
    - imageio
    - kiwisolver
    - mako
    - markdown
    - markupsafe
    - matplotlib-base
    - networkx
    - nibabel
    - numpy
    - opencv
    - packaging
    - pandas
    - pillow
    - pyparsing
    - python >=3.6
    - python-dateutil
    - pytz
    - pywavelets
    - scikit-image
    - scipy
    - simpleitk
    - six

test:
  imports:
    - medcam

about:
  home: https://pypi.org/project/medcam/
  summary: An easy to use library that makes model predictions more interpretable for humans.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://meclabtuda.github.io/M3d-Cam
  dev_url: https://github.com/MECLabTUDA/M3d-Cam

extra:
  recipe-maintainers:
    - sarthakpati
